### ISSUE TITLE
Si el usuario ingresa un valor incorrecto en el input de f(x) se le debería indicar con un mensaje de error

### ISSUE THREAD

**Issue by edme88** [UCC-LabCompu2/proyecto2023-carbel-ditomaso#1]
Si el usuario ingresa valores que no pueden ser graficados, debería mostrarse un `<dialog>` o alert que indique que los valores ingresados son incorrectos, y además, se blanquee/borre el campo ingresado incorrectamente.
![imagen](https://github.com/UCC-LabCompu2/proyecto2023-carbel-ditomaso/assets/8345007/87dfb194-d4cd-4349-9ed8-f8268f37e7ba)

**Comment by agustindt** [comment]
se ha implemntado un mensaje de error tanto en la consola como en el DOM. 

![image](https://github.com/UCC-LabCompu2/proyecto2023-carbel-ditomaso/assets/53263601/3f601a3a-5a1b-4f6d-8594-ad0b2b902ab3)
