### ISSUE TITLE
Las gráficas de constantes se visualizan desplazadas

### ISSUE THREAD

**Issue by edme88** [UCC-LabCompu2/proyecto2023-carbel-ditomaso#11]
![imagen](https://github.com/UCC-LabCompu2/proyecto2023-carbel-ditomaso/assets/8345007/bc139ca2-5c97-4d92-b579-eeeb53391692)

**Comment by agustindt** [comment]
![image](https://github.com/UCC-LabCompu2/proyecto2023-carbel-ditomaso/assets/53263601/39a4ce3f-be8d-4d4e-84ef-4f053a0f7208)
