### ISSUE TITLE
Se debe emplear var, let o const según corresponda para mayor eficiencia

### ISSUE THREAD

**Issue by edme88** [UCC-LabCompu2/proyecto2023-carbel-ditomaso#12]
https://github.com/UCC-LabCompu2/proyecto2023-carbel-ditomaso/blob/3f88e20821998e1f7e60321d814dfcd1c5d52244/script.js#L2-L11

**Comment by agustindt** [comment]
![image](https://github.com/UCC-LabCompu2/proyecto2023-carbel-ditomaso/assets/53263601/363f0b71-c054-486f-a3b5-683575bd297e)
