### ISSUE TITLE
Las gráficas no se realizan de manera completa

### ISSUE THREAD

**Issue by edme88** [UCC-LabCompu2/proyecto2023-carbel-ditomaso#3]
Cuando se ingresa una constante, como 2, la gráfica se inicia en -10 en lugar de iniciar desde el comienzo del canvas.
![imagen](https://github.com/UCC-LabCompu2/proyecto2023-carbel-ditomaso/assets/8345007/bc68ec54-24c5-4c45-a632-43c608f2d31d)

**Comment by agustindt** [comment]
Se ha corregido el recorrido del trazo para que entre completamente en el canvas. Ejemplo: 

![image](https://github.com/UCC-LabCompu2/proyecto2023-carbel-ditomaso/assets/53263601/c9154db8-1735-40eb-9c2e-631ee8f9b1e2)
