### ISSUE TITLE
Las gráficas no se realizan de manera correcta (ejemplo)

### ISSUE THREAD

**Issue by edme88** [UCC-LabCompu2/proyecto2023-carbel-ditomaso#4]
![imagen](https://github.com/UCC-LabCompu2/proyecto2023-carbel-ditomaso/assets/8345007/39d7ab03-51ae-476a-abec-2de2e9d1e362)

**Comment by edme88** [comment]
Si no es válido "3x^2" deberían poner en el ejemplo "3x*x" para que el usuario entienda como emplearlo
![imagen](https://github.com/UCC-LabCompu2/proyecto2023-carbel-ditomaso/assets/8345007/33e58e7a-63e6-4cc3-8b15-fd6584e1250a)

**Comment by agustindt** [comment]
![Captura de pantalla 2023-12-01 090507](https://github.com/UCC-LabCompu2/proyecto2023-carbel-ditomaso/assets/53263601/235b0f86-6dcc-45d3-b0a7-e3f4c0fd4275)

Se ha corregido el grafico de las funciones. Ejemplo: 

![image](https://github.com/UCC-LabCompu2/proyecto2023-carbel-ditomaso/assets/53263601/675acd6d-fda1-4981-9b7d-2803a79e8f0c)
