### ISSUE TITLE
Si la gráfica está fuera de la zona de dibujo se le debe advertir al usuario que no va a visualizarla

### ISSUE THREAD

**Issue by edme88** [UCC-LabCompu2/proyecto2023-carbel-ditomaso#5]
Si la gráfica está fuera de la zona de dibujo pueden o bien advertir al usuario que no va a visualizarla (mediante un dialog o un alert), ó, marca el campo en rojo y pedirle que ingrese valores válidos.
![imagen](https://github.com/UCC-LabCompu2/proyecto2023-carbel-ditomaso/assets/8345007/2fa601e4-cf00-426f-aa28-a2db04cc791c)

**Comment by agustindt** [comment]
![image](https://github.com/UCC-LabCompu2/proyecto2023-carbel-ditomaso/assets/53263601/0566820f-cecd-48a6-8d31-e5a94f3af597)


Ahora si la grafica se extiende por fuera del canvas , se muestra un manejo de error. Hay que mejorarlo

**Comment by agustindt** [comment]
![image](https://github.com/UCC-LabCompu2/proyecto2023-carbel-ditomaso/assets/53263601/d112192f-7d7e-4bff-94a6-d8652f047fc3)
