### ISSUE TITLE
Si el usuario presiona múltiples veces el botón de graficar, la gráfica no se reinicia (comienza desde donde terminó)

### ISSUE THREAD

**Issue by edme88** [UCC-LabCompu2/proyecto2023-carbel-ditomaso#6]
![imagen](https://github.com/UCC-LabCompu2/proyecto2023-carbel-ditomaso/assets/8345007/5de45e8f-b1e5-4874-b610-0b98c3009981)

**Comment by agustindt** [comment]
De ahora en mas cuando el usuario clickea repetida veces el boton graficar. El grafico no hace nada hasta que la funcion complete su recorrido
