### ISSUE TITLE
TODAS las funciones javaScript deben estar comentadas adecuadamente empleando JsDoc

### ISSUE THREAD

**Issue by edme88** [UCC-LabCompu2/proyecto2023-carbel-ditomaso#7]
Cuando documenten, deben emplear el template:
```
/**
 * Descripción de que hace la función
 * @method Nombre de la función
 * @param {string} ParámetroA - Explicación de que valor almacena ParámetroA
 * @param {number} ParámetroB - Explicación de que valor almacena ParámetroB
 * @return Valor que retorna
 */
```

No se olviden de colocar el `@method` con el nombre de la función
https://github.com/UCC-LabCompu2/proyecto2023-carbel-ditomaso/blob/1b0911e36b9d6862da000bb5a1d57e4661ace13a/script.js#L10

https://github.com/UCC-LabCompu2/proyecto2023-carbel-ditomaso/blob/1b0911e36b9d6862da000bb5a1d57e4661ace13a/script.js#L23

**Comment by agustindt** [comment]
Se ha implementado el uso de JsDoc
![image](https://github.com/UCC-LabCompu2/proyecto2023-carbel-ditomaso/assets/53263601/f8a9841b-e478-4a9d-8bdf-0a04f67537f9)

**Comment by edme88** [comment]
Algunas funciones no están comentadas

**Comment by agustindt** [comment]
todas las funciones deberian estar comentadas ahora con el JsDoc
